### ISSUE TITLE
Usability

### ISSUE THREAD

**Issue by sphh** [kuesji/link_eye#10]
Thanks @kuesji for updating the app!

I have some troubles regarding the new usability:

- Whenever I press a link, `link eye` starts, but has the focus in the edit field. This pops up the onscreen keyboard, obscuring the list of available browsers:
![Screenshot_20210901-114504](https://user-images.githubusercontent.com/4856462/131656348-64547a3e-0a1f-46c4-ae9c-590e9b6bc69a.png)
Most of the time I don't want to edit the link, so I would prefer for the keyboard to not pop up:
![Screenshot_20210901-114521](https://user-images.githubusercontent.com/4856462/131656556-4d892aba-7e97-42f2-b1fb-0eb3f9c3f6ee.png)
- `link eye` is presented in the list of browsers. Tapping on it just opens the `link eye` window again without any new possibilities. Could the `link eye` entry be removed from the list of available browsers?
- After I have opened the link in the browser, I return to the app, which requested the opening. The `link eye` window is still there. Would it be possible to close the `link eye` window after it did its duty?

Some more glitches regarding small screens are mentioned in https://github.com/kuesji/link_eye/issues/9#issuecomment-910146261. Mainly the large font size of the widgets surrounding the browser list makes it difficult to use.

**Comment by kuesji** [comment]
thanks for feedback. i will fix these issues soon.

**Comment by Gitoffthelawn** [comment]
Thank you for this great tool.  Like @sphh, I came here partially to recommend removing "link eye" from the list of available browsers since it just links back to itself. 

Thanks!

**Comment by kuesji** [comment]
this issue is fixed. you can wait fdroid version or get apk from app/release folder.

**Comment by sphh** [comment]
Thanks, @kuesji!

Since the `.apk` downloaded from https://github.com/kuesji/link_eye/app/release fails to install on my phone, I'll have to wait (impatiently) for F-Droid (is installs perfectly fine from there).

**Comment by kuesji** [comment]
yes, you must wait. my apk signed with my own key and this makes error if you already installed fdroid version which signed by fdroid's key.

**Comment by Gitoffthelawn** [comment]
Thank you!  Looking forward to F-Droid release.

**Comment by sphh** [comment]
> my apk signed with my own key and this makes error if you already installed fdroid version which signed by fdroid's key.

Ok, that is the reason! I de-installed the F-Droid-version and installed your version.

It improved a lot! Thanks!!

But I noticed, that the keyboard still pops up. Maybe this happens, because I don't use the default keyboard? I tried it with AnySoftKeyboard and FlorisBoard. Both keyboards are shown, whenever `Link Eye` opens. (Should I open another issue?)

Here is a screenshot made on my tiny screen:
![Screenshot_20210905-171347](https://user-images.githubusercontent.com/4856462/132131870-de3cacb9-1285-4c94-8261-10a836a5478b.png)

I wonder, why there is such a big difference between the font sizes of the browser list and all other fonts. I would have thought, the browser list is more important than the "open with" text (and maybe the "link eye" title)? I tried to find another app, where the fonts stay in proportion and found this (it is not a list with icons, but it shows a title, a list and some buttons):
![Screenshot_20210905-172057](https://user-images.githubusercontent.com/4856462/132132135-b6781f32-9182-441b-9646-a122c90e3d8a.png)
(It is from the Transportr app.)

What do you think?

**Comment by kuesji** [comment]
looks like this issue occurs due my bad font size choice. i will fix tonight.

**Comment by kuesji** [comment]
i think it's fixed now. you can check by using this [apk](https://github.com/kuesji/link_eye/tree/master/app/release)

**Comment by sphh** [comment]
Thanks!!! It's much, much better:
![Screenshot_20210906-161337](https://user-images.githubusercontent.com/4856462/132230925-a95a5062-e312-4912-b7d3-053d7661933d.png)

Personally I would like the `link eye` to be the same size as `open with` (and bold). I would also like to have all the text (`link eye`, `open with` and button text) to be the same size, preferably the size of the text on the buttons.

I know, what `copy`, `share` and `close` does. `clean` looks not to do anything (but maybe the uri is already clean?). `requery url` also seems to have no effect on my phone.

My personal preference would be to have all buttons grouped together and near the uri entry box, because they are dealing with the uri displayed in the entry field (at least that's how I understand it). Since `close` duplicates the phone's `back` button, it could be omitted (on small screen)?

What do you think?

One last thing: The entry box still has the focus and pops up the keyboard on my phone.

**Comment by kuesji** [comment]
- "requery url" button is effective when you edit url. it gets which app can handle this url and show in "open with" section.
- copy, share, close, clean will stay at the bottom because user uses this buttons more often editing url and bottom section is more reachable than below of url area.
- link eye is brand and i like the idea of brand is bigger than other elements ( at least in this app )

i don't know how to fix focus issue because i can't reproduce on my own and i already clearing focus on start.

**Comment by sphh** [comment]
I know, this is your app, but most of the famous apps do neither show their name nor the link to the money box in the main window …

Anyway, what do you think to automatically update the list of available apps to open a link based on the first part of the uri? That should be quite easy to do and you could get rid of the `requery url` button. Here is the the idea in more details:
- Attach the `requery url` function to the keypress event in the entry box.
- This monitors changes of the first part of the uri (`https:`, `mailto:` etc) and updates the list of suitable applications.

And BTW: All apps showing a second screen (and `link eye` gives you this very feel) has a left pointing arrow at the top to return to the previous screen. It seems that this is the standard nowadays. Also they often show standardized icons for `share` and `copy` at the top. Would it be possible to make this an option? Then you would have a very clean layout:
- Top line: ← link eye [copy icon][share icon][clean icon]⋮
- Entry box with the editable link
- List of applications suitable to open the link above (because this is updated automatically)

The ⋮ opens the help, about, etc menu.

**Comment by Efreak** [comment]
I'd agree with what @sphh said here, but I'd go even further: reduce the paint at the top and bottom of the screen. This is an app with a functional purpose, so while making it look nice is acceptable, it shouldn't have unused space below the text box and above/below the footer. I'd aarch64 that the donation link should actually be an icon at top right (both to keep it out of the way and make it more obvious to those not reading, as other apps do similar things. This would also help to make the app more useful on smaller screens, for example in the split screen issue.
