### ISSUE TITLE
(feature request) bigger size for options

### ISSUE THREAD

**Issue by nihalanand697** [kuesji/link_eye#10]
Hi, love the app.
Is it possible to make the icons of available apps bigger/having more space between two apps? a setting to resize or by default , anything would do.
+ a grid would be nice too , attaching the screenshots to make it clear.
![Screenshot_20220724-032855_Better Open With~01](https://user-images.githubusercontent.com/47318989/180624286-b0d08ce3-6d0b-4c0f-92e7-264db8d34ff5.png)
![Screenshot_20220724-032931_Better Open With~01](https://user-images.githubusercontent.com/47318989/180624297-dd462f53-17f4-468d-9bcd-6ce2df9ca91c.png)

**Comment by kuesji** [comment]
this screen not coming from link eye, it's your android system's ui.
link eye can't do anything in there.

**Comment by nihalanand697** [comment]
no no, this screen is from another app like link eye. I just shared them to give an idea of what i am talking about.

**Comment by nihalanand697** [comment]
Hi any replies ?

**Comment by nihalanand697** [comment]
hello, I think I was unable to explain myself, can we discuss it?
