### ISSUE TITLE
Suggestion: don't automatically kill the activity

### ISSUE THREAD

**Issue by saalkom** [kuesji/link_eye#11]
If a WebView window is opened from within link eye, pressing the recents or home button has the unfortunate side-effect of also closing WebViews.

link eye 2.0
Android 11
Samsung SM-G991B
One UI 3.1

**Comment by kuesji** [comment]
link eye's intented behaviour is kill itself after launch target application. link eye isn't a long running process.
btw, when user hits back key they wants to exit from app most of time.

**Comment by saalkom** [comment]
Well it also seems to inadvertently kill the target application a lot of the time, if the recents or home buttons are pressed, which is a pretty glaring problem. By the way, I've found this isn't just WebView-specific, but it also occurs for example when I press the recents or home button after Barinsta or Instagram are launched via link eye, and I assume it also happens to pretty much any other target app too. Please watch the video below and notice how apps that are opened via link eye close spontaneously on the recents screen without user interaction. I hope you'll reopen this issue.

https://user-images.githubusercontent.com/44572533/132209636-fa0bd5af-9966-48ad-9757-0b9dd098a2b6.mp4

**Comment by kuesji** [comment]
oh, okay. i'm able to reproduce bug now. i will look what i can do for this.

**Comment by kuesji** [comment]
i think it's fixed now. you can check by using this [apk](https://github.com/kuesji/link_eye/tree/master/app/release)

**Comment by saalkom** [comment]
I've been using that apk for a few days now, with no major issue. The target apps do stay on the recents screen, however the content of some target apps refreshes every time you switch to another app then switch back to the target app.

To again use the specific example of Barinsta and Instagram, if you open someone's Instagram profiles in either app through link eye, the target app (i.e. Barinsta or Instagram) stays open after pressing the recents button, but, upon returning to the target app, the Instagram profile always re-loads. This is abnormal behaviour for both Barinsta and Instagram, and I've only seen it happen when they're opened by link eye.

Still, more testing is needed before I can say that this sort of behaviour is caused by link eye. I'll update this issue if I notice any similar behaviour when switching back to other target apps opened by link eye.
