### ISSUE TITLE
Allow specifying which browsers to show in link eye

### ISSUE THREAD

**Issue by Gitoffthelawn** [kuesji/link_eye#12]
Can you allow the user to specify which browsers to show in link eye?

I never use the pre-installed web browsers that come with Android, so I would like to remove them from link eye.

This will also resolve the first half of https://github.com/kuesji/link_eye/issues/10

Thanks!

**Comment by kuesji** [comment]
i think removing or disabling unused app(s) is better idea than adding hide option to link eye.

**Comment by Gitoffthelawn** [comment]
I wish that was possible, but pre-installed apps cannot be removed without root, and root is not possible (or sometimes desirable) on many devices.

**Comment by kuesji** [comment]
maybe you need to check this [xda-link](https://www.xda-developers.com/uninstall-carrier-oem-bloatware-without-root-access/)

**Comment by Gitoffthelawn** [comment]
Thank you for the link.  My concern with such a technique is the big warning:

> **Uninstalling some system apps can be dangerous and may result in force closes or even a bricked device. An app may depend on another app to work so be careful about what you uninstall and the consequences it may have.**

Since the outcome can be a bricked device, the risk seems to outweigh the benefit.

**Comment by Efreak** [comment]
There's another reason for this: I've got several apps installed that are technically capable of opening urls, but I only use them as share targets; I want to keep them installed, however I never want to use them to open urls. For example, a text editor, a file browser (implements share to save file and open URL to preview image). Other apps are like my media player, which can open urls, but I only use them to open local files. Every time I open an mp3 URL, I get BubbleUPnP and others, while I don't actually use these apps to open media directly.

**Comment by yephny** [comment]
Can't you go to the settings of those apps and set it to "don't open links in this app"? It removes the app from link eye in my case.
