### ISSUE TITLE
Bug: Link not opening

### ISSUE THREAD

**Issue by alenpaul2001** [kuesji/link_eye#2]
I been using link eye for past two days, The launching is skipped when opening links from a particular application.
The issue can be fixed by opening and closing link eye.

application I am having issue with - [NekogramX](https://github.com/NekoX-Dev/NekoX) a telegram client

**Comment by alenpaul2001** [comment]
https://user-images.githubusercontent.com/38587581/163201439-ce844c1f-3758-4111-94ba-40fa483bfd98.mp4

**Comment by kuesji** [comment]
do you have same issue with other apps at open? 
brave and/or chrome is working as expected or not?

**Comment by alenpaul2001** [comment]
> do you have same issue with other apps at open? brave and/or chrome is working as expected or not?

- no so far I didn't noticed same issue in other apps. 
- none of the intents are working

**Comment by kuesji** [comment]
i can't reproduce this bug on my test phone. bromite & firefox works as expected.
i have an idea and maybe it can fix your problem but you need test for me. i will ping you when it's ready.

**Comment by kuesji** [comment]
please test this and inform me.
[link_eye.zip](https://github.com/kuesji/link_eye/files/8488886/link_eye.zip)

**Comment by alenpaul2001** [comment]
> please test this and inform me.
> [link_eye.zip](https://github.com/kuesji/link_eye/files/8488886/link_eye.zip)
> 

yeah this is working as expected, I will report back any issues after using it for one day.

**Comment by kuesji** [comment]
i will send update to fdroid in few days and it will updated in next week probably.
you can use github version until fdroid update ( available at releases ).

**Comment by alenpaul2001** [comment]
> i will send update to fdroid in few days and it will updated in next week probably.
> you can use github version until fdroid update ( available at releases ).

got say its working as a charm. thanks for the fix, much appreciated.

**Comment by AntoninCurtit** [comment]
Hi !
I've encountered this issue on Twitter. I have l.-e. since 2 weeks, and I can't open any link in there.
Once I've taped to open it or share it, nothing happen. Tho, Links are added to the history. 🤔

**Comment by alenpaul2001** [comment]
> Hi ! I've encountered this issue on Twitter. I have l.-e. since 2 weeks, and I can't open any link in there. Once I've taped to open it or share it, nothing happen. Tho, Links are added to the history. thinking

are you using the latest version?

**Comment by AntoninCurtit** [comment]
v1.0 from F-Droid, yes

**Comment by alenpaul2001** [comment]
> v1.0 from F-Droid, yes

check the github release, v1.1 is released with the fix.
