### ISSUE TITLE
Feature request: auto update applications based on link

### ISSUE THREAD

**Issue by alenpaul2001** [kuesji/link_eye#3]
This is a request for auto updating the preferred application when the link in the text box changes.

current behaviour :- the applications does not change at all even though the link is changed by the user.

https://user-images.githubusercontent.com/38587581/163957022-f7bc4f57-fe5a-44bc-81d9-e9f44778f045.mp4

**Comment by kuesji** [comment]
actually this is bug report instead of feature request. 
looks like i forgot the implement this because i planned this feature at the start of project.

i'm bit busy at the moment and will probably fix this later (maybe at weekend).

**Comment by kuesji** [comment]
fixed at v1.2 update.
