### ISSUE TITLE
use popup instead when opening links

### ISSUE THREAD

**Issue by pokegamer5547** [kuesji/link_eye#6]
I recently found this app and i really like how i can copy the link.
But i think the app entitely showing up on screen is little unnecessary. Maybe you can make a popup instead of opening whole app. 
I overall like this and looking forward to see it improve. :)

**Comment by kuesji** [comment]
it's not bad idea but i like current approach more and don't want to change working system or add another option.

**Comment by pokegamer5547** [comment]
> it's not bad idea but i like current approach more and don't want to change working system or add another option.

Oh it's alright, i respect your decision and yep current design is pretty good too.
