### ISSUE TITLE
Link eye should close if the back button is pressed or the user taps the unused space above the dialog box

### ISSUE THREAD

**Issue by saalkom** [kuesji/link_eye#6]
The current behaviour (having no option but the close button) is a little unintuitive.

Great little app though — I didn't realise how much I would appreciate being able to inspect the URLs I was opening in other apps until now. It also complements Easy Open Link quite nicely.

**Comment by kuesji** [comment]
this behaviour is my fauly due my lazyness and it wil be fixed in next release.
i'm closing issue for now.
