### ISSUE TITLE
UI usability on smaller screen

### ISSUE THREAD

**Issue by GoldenHashtag** [kuesji/link_eye#9]
link eye is nearly unusable in split-screen view:
![Screenshot_20210901_164958_kuesji link_eye~2](https://user-images.githubusercontent.com/40300931/131642267-01ff0c58-edda-445e-912b-71aba148a050.jpg)
Link address should be scrollable together with the whole UI, also link address should only take one line and expandable by tapping on it (make a visual tip so user know tapping on it shows full address).

Also text wraps around on devices with larger scale settings (smaller screen):
![Screenshot_20210901_162612_kuesji link_eye~2](https://user-images.githubusercontent.com/40300931/131642239-f1727b0a-1348-4096-9336-f205bcee0f5f.jpg)
maybe enlarge button width size and make button warp (2x2 grid or 1x4 stack) instead on smaller screen would be the better approach?

**Comment by sphh** [comment]
I can only support @GoldenHashtag:
That's how it looks on my (admittedly very tiny) screen:
![Screenshot_20210901-114521](https://user-images.githubusercontent.com/4856462/131654628-f1cd74e5-2dea-40af-a2ef-88301ad3eb89.png)

I would like to see the following improvements:
- Remove the `link eye` text at the top of the screen
- Move the `query` button to the bottom (BTW what does `query` actually do?)
- Show the buttons at the bottom
- Adapt the font size

**Comment by kuesji** [comment]
i don't have enough time to work for small screens.
so, i just disabled split screen ability for link eye.
